### ISSUE TITLE
执行项目后无任何响应

### ISSUE THREAD

**Issue by ss098** [keenwon/antcolony#1]
我希望部署您的项目 AntColon，根据 Readme.md 中提到的安装了环境 NodeJS、MongoDB、Redis、Elasticsearch、PM2，并且配置了 config.js。

执行命令 node startup worker 3000 并没有得到任何反应，我并没有使用过 pm2，使用据我推测的命令 pm2 list 得到的列表里并没有应用，简单阅读了应用的源代码我仍然没有任何头绪。

[cenegd@iZ28acwb340Z antcolony-master]$ node startup worker 3000
[cenegd@iZ28acwb340Z antcolony-master]$
[cenegd@iZ28acwb340Z antcolony-master]$ pm2 list
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬────────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ memory │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
[cenegd@iZ28acwb340Z antcolony-master]$

**Comment by keenwon** [comment]
这样不大看的出来，尝试这几个方法：
1、确认[config.js](https://github.com/keenwon/antcolony/blob/master/config.js#L44)文件有没有配置端口号是3000的worker，还有服务器有没有开放3000端口。
2、试一下pm2有没有安装正确，写个js用pm2启动试试，参考[这里](https://github.com/Unitech/pm2#startup-script-generation) 。
3、看一下pm2的日志，有没有什么错误信息`pm2 logs`。
4、看一下AntColony的log下面有没有什么异常信息

**Comment by ss098** [comment]
重新启动了系统并运行了相关环境，再次执行 node startup queen 3001 得到如下结果。
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
我查看 MongoDB 中并没有相关的数据。

> use bt
> switched to db bt
> show collections
> system.indexes
> system.users

请问希望取得数据应该怎样操作。

附 config.js
https://gist.github.com/ss098/185f4a65dd664f0aa074

**Comment by keenwon** [comment]
就算运行起来，也不会马上又数据的。
而且你只启动了worker，你执行`pm2 monit`或者看下redis里的统计信息，就知道worker有没有在工作了。
如果一切正常的话，把`female`和`male`也启动起来，等一段时间mongodb才能有数据。

**Comment by ss098** [comment]
运行了 female 和 male，状态跟最早提到的没有返回数据直接换行是一样的，然后查询了 Redis 与 pm2。

[cenegd@iZ28acwb340Z antcolony-master]$ redis-cli
redis 127.0.0.1:6379> keys *
(empty list or set)
redis 127.0.0.1:6379>

⌬ PM2 monitoring :

（pm2 monit 里是空的）

执行 pm2 list 中列表仍然是空的，是否是没有成功运行应用？

这么晚了还在打扰你的休息，实在抱歉。

**Comment by keenwon** [comment]
我估计是你是根本没启来，起来的话pm2会显示的。
等我明天运行一遍，写个详细的教程。

**Comment by ss098** [comment]
好的，谢谢，打扰了，期待着你的教程。

**Comment by keenwon** [comment]
看这个[文档](https://github.com/keenwon/antcolony/blob/master/doc/%E9%83%A8%E7%BD%B2%E6%96%87%E6%A1%A3.md)

**Comment by keenwon** [comment]
如果还有问题再提
