### ISSUE TITLE
目前代码生成后，elasticsearch是每天手动更新还是自动更新的，

### ISSUE THREAD

**Issue by talway** [keenwon/antcolony#13]
目前代码生成后，elasticsearch是每天手动更新还是自动更新的，

都更新些什么内容，占用空间大吗？

**Comment by keenwon** [comment]
Elasticsearch的操作没有包括在AntColony中
之前有尝试过，在插入数据库的同时，也写进Elasticsearch，但是两个都是异步操作，效率太低
