### ISSUE TITLE
MongoDB River Plugin for ElasticSearch 

### ISSUE THREAD

**Issue by talway** [keenwon/antcolony#15]
ElasticSearch  定期同步插件形式，你试试，
https://github.com/richardwilly98/elasticsearch-river-mongodb/

通过ElasticSearch 定期同步MongoDB 数据库，你测试下如何，性能

**Comment by keenwon** [comment]
这个之前考虑过，但是它貌似要求有一个mongodb副本集，所以放弃了，因为mongodb实在是太占硬盘了
以后再有项目得考虑考虑mongodb的替代方案了

**Comment by talway** [comment]
是要集群的；现在爬了些，你300w 是占多大空间，我的
resources
{
        "ns" : "antcolony.resources",
        "count" : 518524,
        "size" : 1351113088,
        "avgObjSize" : 2605,
        "storageSize" : 1450037248,
        "numExtents" : 20,
        "nindexes" : 1,
        "lastExtentSize" : 378707968,
        "paddingFactor" : 1,
        "systemFlags" : 0,
        "userFlags" : 1,
        "totalIndexSize" : 44199456,
        "indexSizes" : {
                "_id_" : 44199456
        },
        "ok" : 1
}

**Comment by keenwon** [comment]
```
{
    "db" : "antcolony",
    "collections" : 3,
    "objects" : 3124345,
    "avgObjSize" : 2774.753671569561,
    "dataSize" : 8669287760,
    "storageSize" : 9999605744,
    "numExtents" : 26,
    "indexes" : 2,
    "indexSize" : 262408720,
    "fileSize" : 12812550144,
    "nsSizeMB" : 16,
    "dataFileVersion" : {
        "major" : 4,
        "minor" : 5
    },
    "extentFreeList" : {
        "num" : 0,
        "totalSize" : 0
    },
    "ok" : 1
}
```
