### ISSUE TITLE
mac os error

### ISSUE THREAD

**Issue by hktalent** [keenwon/antcolony#20]
Error: Cannot find module 'winston'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)

$ npm install -g winston

is ok

**Comment by hktalent** [comment]
没有错误消息
$ pm2 status
┌──────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
│ App name     │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ watching │
├──────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ female[1]    │ 3  │ fork │ 99040 │ online │ 231     │ 1s     │ 62% │ 48.5 MB   │ disabled │
│ male[1]      │ 2  │ fork │ 99041 │ online │ 245     │ 0s     │ 58% │ 41.4 MB   │ disabled │
│ worker[3000] │ 0  │ fork │ 99022 │ online │ 258     │ 1s     │ 60% │ 51.0 MB   │ disabled │
│ worker[3001] │ 1  │ fork │ 99005 │ online │ 249     │ 1s     │ 58% │ 60.5 MB   │ disabled │
└──────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
但是不停的restart
没有数据

**Comment by keenwon** [comment]
不是`npm install -g winston`，是在antcolony的package.json所在的目录执行`npm install winston`
