### ISSUE TITLE
没有数据

### ISSUE THREAD

**Issue by 6api** [keenwon/antcolony#21]
pm2运行显示正常
redis里有数据，但.temp和mongodb没有数据
male 和 female也运行了的
日志里也没有错误，怎么回事

**Comment by keenwon** [comment]
运行了多久了？

**Comment by 6api** [comment]
一小时左右吧，redis里大概1，2百个bucket了

**Comment by keenwon** [comment]
看下pm2日志报什么错没

**Comment by justein** [comment]
一直停留在 Starting pm2 daemon。。。日志也没报错，显示 starting all nodes process。。。完全按照文档来作的

**Comment by landolphin** [comment]
兄弟和我一样  pm2运行显示正常 但是mongodb里没有数据 但是在redis里bucket  remoteNodes 和 sysInfo 有数据。

**Comment by keenwon** [comment]
@landolphin
看一下 .temp 里面有没有种子文件，如果没有的话，试一下机器到 http://torcache.net 通不通

**Comment by landolphin** [comment]
unknown host http://torcache.net  怎么破

**Comment by landolphin** [comment]
我的是HK服务器 按说不会被大陆强啊

**Comment by keenwon** [comment]
https://github.com/keenwon/antcolony/blob/master/src/male.js#L27

不一定是被墙，可能是不服务了
你在上面代码的注释里找找有的有能用的，或者网上搜索下

**Comment by landolphin** [comment]
多谢大神

**Comment by landolphin** [comment]
util.format('http://zoink.it/torrent/%s.torrent', _infohash)  换成这个节点了  跑一会试试看。 这个网址我服务器可以ping的通

**Comment by keenwon** [comment]
close. 有问题重新再提
