### ISSUE TITLE
搭建成功，可以跑到infohash 但是无法下载

### ISSUE THREAD

**Issue by landolphin** [keenwon/antcolony#23]
// util.format('http://zoink.it/torrent/%s.torrent', _infohash),
                // util.format('http://bt.box.n0808.com/%s/%s/%s.torrent', _infohash.substr(0, 2), _infohash.substr(_infohash.length - 2, 2), _infohash),
                // util.format('http://torrage.com/torrent/%s.torrent', _infohash),
                // util.format('http://torrage.luisaranguren.com/torrent/%s.torrent', _infohash),
                util.format('http://thetorrent.org/%s.torrent', _infohash)

这些地址貌似都过期了。我手动上传种子torrent 到.temp目录里，可以解析 但是就是无法下载。求大神推荐个可以下载的torrent托管站

**Comment by keenwon** [comment]
这个你得自己搜一搜了，我已经好久没玩这个了。
搜到了分享下 :smile:
