### ISSUE TITLE
dist目录下就是用来部署的文件--能否把这个文件发出来

### ISSUE THREAD

**Issue by talway** [keenwon/antcolony#8]
dist目录下就是用来部署的文件--能否把这个文件发出来

**Comment by keenwon** [comment]
建议按照[部署文档](https://github.com/keenwon/antcolony/blob/master/doc/%E9%83%A8%E7%BD%B2%E6%96%87%E6%A1%A3.md)进行编译

**Comment by talway** [comment]
grunt 没安装，已搞定
